version: '3.5'
services:
  postgres:
    image: postgres:14.4-alpine
    platform: linux/x86_64
    container_name: postgres_spring_coroutines
    ports:
      - '5432:5432'
    volumes:
      - ./application/src/main/resources/schema.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: root
      PGUSER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
